### numpy.arrary合并与分割
#### concatenate 合并

In [4]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [6]:
z = np.concatenate([x, y]);
z

array([1, 2, 3, 3, 2, 1])

In [12]:
A = np.array([[3, 4, 5],[6, 7, 8]])
A

array([[3, 4, 5],
       [6, 7, 8]])

In [19]:
B = np.array([[1, 2, 3], [3, 4, 5]])
B

array([[1, 2, 3],
       [3, 4, 5]])

In [20]:
C = np.concatenate([A, B])
C

array([[3, 4, 5],
       [6, 7, 8],
       [1, 2, 3],
       [3, 4, 5]])

In [21]:
D = np.concatenate([A, B], axis = 1)
D

array([[3, 4, 5, 1, 2, 3],
       [6, 7, 8, 3, 4, 5]])

#### vstack --- 垂直合并（加行向量）

In [22]:
D = np.vstack([A, B, x])
D

array([[3, 4, 5],
       [6, 7, 8],
       [1, 2, 3],
       [3, 4, 5],
       [1, 2, 3]])

#### hstack ---- 水平合并（加列向量）

In [31]:
a = np.full((2, 1), 6)
a

array([[6],
       [6]])

In [32]:
b = np.hstack([A, a])
b

array([[3, 4, 5, 6],
       [6, 7, 8, 6]])

#### split --- 分割

In [33]:
x = np.arange(8).reshape(2, 4)
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
x1, x2 = np.split(x, [-1])
x1

array([[0, 1, 2, 3]])

In [35]:
x2

array([[4, 5, 6, 7]])

In [36]:
x3, x4 = np.split(x, [2], axis = 1)
x3

array([[0, 1],
       [4, 5]])

In [37]:
x4

array([[2, 3],
       [6, 7]])

#### vsplit --- 垂直分割（按行向量分割）

In [39]:
x1, x2 = np.vsplit(x, [-1])
x1

array([[0, 1, 2, 3]])

In [40]:
x2

array([[4, 5, 6, 7]])

#### hsplit --- 水平分割（按列向量分割）

In [41]:
x3, x4 = np.hsplit(x, [2])
x3

array([[0, 1],
       [4, 5]])

In [42]:
x4

array([[2, 3],
       [6, 7]])

In [44]:
x4[: , 0]

array([2, 6])