### numpy 矩阵的比较

In [1]:
import numpy as np

In [7]:
x = np.arange(16)
np.random.shuffle(x)
x

array([ 5,  6,  1,  8, 13, 14,  3,  0, 15,  2, 11,  4,  7, 10,  9, 12])

In [9]:
X = np.reshape(x, (4, -1))
X

array([[ 5,  6,  1,  8],
       [13, 14,  3,  0],
       [15,  2, 11,  4],
       [ 7, 10,  9, 12]])

In [10]:
x > 3

array([ True,  True, False,  True,  True,  True, False, False,  True,
       False,  True,  True,  True,  True,  True,  True])

In [11]:
X > 3

array([[ True,  True, False,  True],
       [ True,  True, False, False],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [12]:
np.sum(x > 3)

12

In [15]:
np.sum(X > 3, axis = 0)

array([4, 3, 2, 3])

In [16]:
np.any(x <= 0)## x中有一个小于等于0就为true

True

In [18]:
np.all(x > 0)## x中所有元素都要大于0才为true

False

In [19]:
## 多种条件判断要用 & | ~ 位比较运算符而不用&& 等逻辑比较符
np.sum((x > 3) & (x < 10))

6

In [20]:
np.sum((x > 3) && (x < 10))

SyntaxError: invalid syntax (<ipython-input-20-d834f65999a2>, line 1)

In [21]:
x[x > 7]

array([ 8, 13, 14, 15, 11, 10,  9, 12])

In [22]:
## X中取出最后一列能被3整除所在行
X[X[: , 3] % 3 == 0, :]

array([[13, 14,  3,  0],
       [ 7, 10,  9, 12]])