### 矩阵基本运算

In [1]:
import numpy as np

#### 通用运算

In [4]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
a + 1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [6]:
a - 1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [7]:
a * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

\+ \- \* / (\*\* //) 等，矩阵和数字的计算
还有些基本的数学函数

In [8]:
np.exp2(a)

array([[1.0000e+00, 2.0000e+00, 4.0000e+00, 8.0000e+00],
       [1.6000e+01, 3.2000e+01, 6.4000e+01, 1.2800e+02],
       [2.5600e+02, 5.1200e+02, 1.0240e+03, 2.0480e+03],
       [4.0960e+03, 8.1920e+03, 1.6384e+04, 3.2768e+04]])

#### 矩阵运算

In [10]:
b = np.arange(16).reshape(4, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
# + - * / 都是对应项运算
a + b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [16]:
a * b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [18]:
# 矩阵乘法调用dot()函数
a.dot(b)

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506]])

In [20]:
# 矩阵转置
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [22]:
c = a.T 
c[0, 0] = 1
a
# 转置也是类似引用的方式

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
c = a.T.copy()
c[0, 0] = 0
a
#运用copy

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### BroadCasting 原则
整体而言，两个不同形状的矩阵（或者向量）进行基本运算，看两个矩阵（或者向量）的倒序维数。如果倒序维数是一致的，则“小矩阵”经过复制扩展，和“大矩阵”进行基本运算。

比如：

A.shape = (2 x 3)  ->  A.shape = (2 x 3)
b.shape = (3)      ->  b.shape = (1 x 3)

A.shape = (2 x 3)  ->  A.shape = (2 x 3)
b.shape = (1)      ->  b.shape = (1 x 1)
但是，在以下例子中，b无法broadcasting后和A进行运算

A.shape = (2 x 3)
b.shape = (1 x 2)

#### 矩阵的逆

In [26]:
a

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
A = np.array([[1, 2],[3, 4]])
A

array([[1, 2],
       [3, 4]])

In [32]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [34]:
A.dot(Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

#### 矩阵伪逆 --- A * B = E 即可，不要求是方阵

In [35]:
x = np.arange(16).reshape(2, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [37]:
pinvX = np.linalg.pinv(x)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [40]:
x.dot(pinvX)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])