### numpy 聚合操作

In [3]:
import numpy as np

#### sum min max

In [11]:
big_array = np.random.rand(1000000)

In [12]:
%timeit np.sum(big_array)

1.08 ms ± 29.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [13]:
np.sum(big_array)

499778.3214425092

In [14]:
np.max(big_array)

0.9999995608596891

In [15]:
np.min(big_array)

1.6750374864926698e-08

In [16]:
big_array.min()

1.6750374864926698e-08

In [18]:
big_array.sum()

499778.3214425092

#### 多维度聚合

In [19]:
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
arr.sum()

120

axis 是维度参数

In [21]:
arr.sum(axis = 1)

array([ 6, 22, 38, 54])

In [22]:
arr.max(axis = 0)

array([12, 13, 14, 15])

#### 其它聚合操作

In [25]:
# 乘积 
np.prod(arr + 1)

2004189184

In [26]:
np.prod(arr, axis = 1)

array([    0,   840,  7920, 32760])

In [27]:
## 平均值 -- mean()
arr.mean()

7.5

In [29]:
## 中位数 -- median()
np.median(arr, axis = 1)

array([ 1.5,  5.5,  9.5, 13.5])

In [32]:
## np.percentile(x, num) 数组或矩阵处于num%的数字
np.percentile(big_array, 30)

0.29922135660226135

In [35]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, percent))

1.6750374864926698e-08
0.24930978273725388
0.4996826928975349
0.7499907332783681
0.9999995608596891


In [36]:
## np.var() --- variance 方差 
np.var(arr)

21.25

In [38]:
## np.std() -- 标准差 stdandard deviation
np.std(arr)

4.6097722286464435