### 关于numpy中对索引的操作

In [1]:
import numpy as np
x = np.random.normal(0, 1, 1000000)

#### arg操作 --- argument

In [2]:
np.argmin(x)

346737

In [3]:
np.min(x)

-4.542771689912339

In [4]:
x[np.argmin(x)]

-4.542771689912339

#### 排序中使用arg

In [6]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.random.shuffle(x)
x

array([ 1, 11,  2, 10,  9, 15, 12,  6,  4, 14,  3,  5,  7,  8, 13,  0])

In [13]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
x

array([ 1, 11,  2, 10,  9, 15, 12,  6,  4, 14,  3,  5,  7,  8, 13,  0])

In [15]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
X = np.random.randint(10, size = (4, 4))
X

array([[4, 6, 8, 7],
       [5, 2, 8, 2],
       [5, 6, 7, 8],
       [0, 1, 5, 2]])

In [19]:
np.sort(X)

array([[4, 6, 7, 8],
       [2, 2, 5, 8],
       [5, 6, 7, 8],
       [0, 1, 2, 5]])

In [20]:
np.sort(X, axis = 0)

array([[0, 1, 5, 2],
       [4, 2, 7, 2],
       [5, 6, 8, 7],
       [5, 6, 8, 8]])

In [22]:
np.random.shuffle(x)
x

array([15, 13,  7, 11,  4, 14,  6,  9,  8,  2,  3,  5,  1,  0, 12, 10])

In [23]:
np.argsort(x)

array([13, 12,  9, 10,  4, 11,  6,  2,  8,  7, 15,  3, 14,  1,  5,  0],
      dtype=int64)

In [24]:
np.partition(x, 5)

array([ 0,  2,  1,  3,  4,  5,  6,  7,  8,  9, 10, 13, 14, 11, 12, 15])

In [25]:
np.argpartition(x, 5)

array([13,  9, 12, 10,  4, 11,  6,  2,  8,  7, 15,  1,  5,  3, 14,  0],
      dtype=int64)

In [26]:
X

array([[4, 6, 8, 7],
       [5, 2, 8, 2],
       [5, 6, 7, 8],
       [0, 1, 5, 2]])

In [28]:
np.sort(X, axis = 0)

array([[0, 1, 5, 2],
       [4, 2, 7, 2],
       [5, 6, 8, 7],
       [5, 6, 8, 8]])

In [29]:
np.argsort(X, axis = 0)

array([[3, 3, 3, 1],
       [0, 1, 2, 3],
       [1, 0, 0, 0],
       [2, 2, 1, 2]], dtype=int64)

In [33]:
np.partition(X, 1, axis = 1)

array([[4, 6, 8, 7],
       [2, 2, 8, 5],
       [5, 6, 7, 8],
       [0, 1, 5, 2]])

In [34]:
x = np.random.randint(20, size = 10)
x

array([15,  8, 12,  2,  3,  2,  5,  3,  8,  5])

In [39]:
## find kth element 
np.partition(x, kth = 9)

array([ 2,  3,  3,  2,  5,  5,  8,  8, 12, 15])

#### Fancy indexing

In [42]:
x = np.arange(16)
np.random.shuffle(x)
x

array([ 3,  5,  2, 11, 15, 12,  9,  7, 10,  1, 14,  6, 13,  4,  8,  0])

In [43]:
x[1:5]

array([ 5,  2, 11, 15])

In [44]:
ind = [3, 5, 7]
x[ind]

array([11, 12,  7])

In [45]:
ind = np.array([[1, 2],[3, 4]])
x[ind]

array([[ 5,  2],
       [11, 15]])

运用在二维数组

In [46]:
X = x.reshape(4, -1)
X

array([[ 3,  5,  2, 11],
       [15, 12,  9,  7],
       [10,  1, 14,  6],
       [13,  4,  8,  0]])

In [50]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([5, 9, 6])

In [51]:
X[:2, col]

array([[ 5,  2, 11],
       [12,  9,  7]])

In [52]:
col = [True, True, False, True]
X[1, col]

array([15, 12,  7])

In [53]:
X[row, col]

array([ 3, 12,  6])

In [54]:
## 有一个问题：如何取row，col对应的方阵 --- 取三行三列，暂时还不知道