### numpy.array 基础

In [2]:
import numpy as np
np.__version__

'1.14.0'

#### python 自带 array

In [3]:
import array
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

#### numpy.array

In [5]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
nparr.dtype

dtype('int32')

In [7]:
nparr2 = np.array([1, 2, 3.0])
nparr2.dtype

dtype('float64')

### 其它创建array方法
#### zeros

In [8]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

默认float类型

In [9]:
np.zeros(shape = (3, 5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### ones 类似

In [10]:
np.ones(shape = (3, 5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### full

In [14]:
np.full(shape = (3, 5), fill_value = 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

#### arange

In [15]:
np.arange?

In [16]:
np.arange(0, 2, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

#### linspace

In [18]:
np.linspace?

In [19]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### random --- randint

In [20]:
np.random.randint(10, size=(3,5))

array([[8, 0, 4, 5, 8],
       [1, 4, 2, 1, 2],
       [0, 9, 4, 5, 4]])

#### random --- seed 

In [21]:
np.random.seed(123)
np.random.randint(10, size=(3,5))

array([[2, 2, 6, 1, 3],
       [9, 6, 1, 0, 1],
       [9, 0, 0, 9, 3]])

In [23]:
np.random.seed(123)
np.random.randint(10, size=(3,5))

array([[2, 2, 6, 1, 3],
       [9, 6, 1, 0, 1],
       [9, 0, 0, 9, 3]])

#### random --- random

In [24]:
help(np.random.random)

Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

#### random --- normal 正态分布

In [25]:
np.random.normal(0, 1, (3, 5))

array([[ 0.80748488, -1.05826725,  1.73002449,  1.23265016, -0.82359837],
       [-0.11820135, -0.57610319,  1.69573072, -0.07439424, -1.90063702],
       [-0.77765486,  1.31346198,  1.80445789, -0.96555003, -1.31648003]])

In [26]:
np.random?