### array 基本操作

In [1]:
import numpy as np
np.__version__

'1.14.0'

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
y = np.arange(15).reshape(3, 5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### numpy.array 基本属性

In [6]:
# 维度
x.ndim 

1

In [7]:
y.ndim

2

In [8]:
# shape 具体维度信息
x.shape

(10,)

In [9]:
y.shape

(3, 5)

In [10]:
# 矩阵大小
x.size

10

#### numpy.array 数据访问

In [11]:
# 不建议使用y[i][j]方式，而使用y[i, j]
y[0, 1]

1

In [12]:
# x[start:end:space] 表达式 访问 x[start ... end) 步长为 space 的数据
x[: 5]

array([0, 1, 2, 3, 4])

In [15]:
x[3: 8 : 2]

array([3, 5, 7])

In [16]:
x[8: 3: -1]

array([8, 7, 6, 5, 4])

In [18]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
y[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [25]:
suby = y[::-1, :2 :-1] # 类似引用方式
suby

array([[14, 13],
       [ 9,  8],
       [ 4,  3]])

In [26]:
suby[0, 0] = 1 
y # 改变suby也会改变y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13,  1]])

In [28]:
# 使用copy()方法来解决问题
suby = y[:2, :3].copy()
suby

array([[0, 1, 2],
       [5, 6, 7]])

In [30]:
suby[0, 0] = 5
suby

array([[5, 1, 2],
       [5, 6, 7]])

In [31]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13,  1]])

#### reshape --- 改变维度具体信息

In [32]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
z = x.reshape(2, 5)
z.ndim

2

In [36]:
x.reshape(5, -1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [37]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)